import assert from 'node:assert/strict';
import {readFile,writeFile} from 'node:fs/promises';
import {database} from './d1-local.mjs';
const source=await readFile(new URL('../dist/server/index.js',import.meta.url),'utf8');
const worker=(await import('data:text/javascript;base64,'+Buffer.from(source).toString('base64'))).default;
const DB=database(),env={DB,GENERATION_MODE:'demo'},tests=[];
const originalNow=Date.now;let now=originalNow();Date.now=()=>now;
async function call(path,body,token){const req=new Request('http://localhost'+path,{method:body?'POST':'GET',headers:{...(body?{'content-type':'application/json'}:{}),...(token?{Authorization:'Bearer '+token}:{})},...(body?{body:JSON.stringify(body)}:{})});const res=await worker.fetch(req,env);return {status:res.status,data:await res.json()};}
const ok=(result,status=200)=>{assert.equal(result.status,status,JSON.stringify(result.data));return result.data;};
const get=async s=>ok(await call('/api/rooms/'+s.code,null,s.token)).room;
const action=async(s,type,extra={})=>{const v=await get(s);return call('/api/rooms/'+s.code+'/action',{type,gameId:v.gameId,roundId:v.roundId,...extra},s.token);};
const raw=code=>JSON.parse(DB.raw.prepare('SELECT state FROM rooms WHERE code=?').get(code).state);
function checked(name,fn){return Promise.resolve().then(fn).then(()=>{tests.push({name,status:'PASS'});console.log('PASS '+name);});}
try{
 const made=ok(await call('/api/rooms',{name:'主催者'}),201),host={code:made.room.code,token:made.token};const sessions=[host];
 for(const name of ['あおい','はな','たろう']){const joined=ok(await call('/api/rooms/'+host.code+'/join',{name}));assert.equal(joined.player,undefined);sessions.push({code:host.code,token:joined.token});}
 await checked('four independent sessions and host authority',async()=>{assert.equal((await get(host)).players.length,4);assert.equal((await action(sessions[1],'start')).status,403);ok(await action(host,'start'));});
 await checked('writing privacy and concurrent submissions',async()=>{const views=await Promise.all(sessions.map(get));assert.equal(new Set(views.map(v=>v.mine.prompt)).size,4);views.forEach(v=>{assert.equal(v.round,undefined);assert.equal(v.mine.answer,'');assert.ok(!JSON.stringify(v).includes('tokenHash'));});const submissions=await Promise.all(sessions.map((s,i)=>action(s,'submit',{answer:'これは私が考えた回答です。番号'+i+'です。'})));submissions.forEach(r=>ok(r));assert.equal((await get(host)).phase,'play');});
 await checked('five equal cards and no pre-reveal answer leak',async()=>{for(const s of sessions){const v=await get(s);assert.equal(v.round.cards.length,5);assert.equal(new Set(v.round.cards.map(c=>c.text)).size,5);assert.equal(v.round.correctCardId,undefined);assert.equal(v.round.authorId,undefined);assert.equal(v.round.votes,undefined);v.round.cards.forEach(c=>assert.deepEqual(Object.keys(c).sort(),['id','text']));}assert.equal((await call('/api/rooms/'+host.code+'/join',{name:'遅刻'})).status,409);});
 let oldRound;
 await checked('simultaneous private votes, exact scores, author cover vote',async()=>{ok(await action(host,'open_vote'));const room=raw(host.code),r=room.rounds[0],correct=r.cards.find(c=>c.human).id,wrong=r.cards.find(c=>!c.human).id;oldRound={gameId:room.gameId,roundId:r.id};let seeker=0;const before=await Promise.all(sessions.map(get));const votes=await Promise.all(sessions.map((s,i)=>{const cardId=before[i].mine.role==='author'?correct:(seeker++===0?correct:wrong);return action(s,'vote',{cardId});}));votes.forEach(v=>ok(v));const v=await get(host);assert.equal(v.phase,'reveal');assert.equal(v.round.authorPoints,133);const author=v.players.find(p=>p.id===v.round.authorId);assert.equal(author.score,133);assert.equal(v.players.reduce((a,p)=>a+p.score,0),233);assert.equal(v.round.votes.length,3);await get(host);assert.equal((await get(host)).players.reduce((a,p)=>a+p.score,0),233);});
 await checked('next is protected from delayed repeat, timeout reveal is once',async()=>{ok(await action(host,'next'));const delayed=await call('/api/rooms/'+host.code+'/action',{type:'next',...oldRound},host.token);assert.equal(delayed.status,409);const before=(await get(host)).players.map(p=>p.score);now=(await get(host)).round.deadline+1;const v=await get(host);assert.equal(v.phase,'reveal');assert.equal(v.round.authorPoints,0);assert.deepEqual(v.players.map(p=>p.score),before);});
 await checked('complete game and rematch return all players to lobby',async()=>{for(let i=0;i<2;i++){ok(await action(host,'next'));now=(await get(host)).round.deadline+1;assert.equal((await get(host)).phase,'reveal');}ok(await action(host,'next'));const done=await get(host);assert.equal(done.phase,'finished');assert.equal(done.highlights.length,4);ok(await action(host,'rematch'));const lobby=await get(host);assert.equal(lobby.phase,'lobby');assert.equal(lobby.players.length,4);assert.ok(lobby.players.every(p=>p.score===0));});
 await checked('host can recover stalled writing and remove absent member',async()=>{ok(await action(host,'start'));ok(await action(host,'reset'));const removed=(await get(sessions[3])).mine.id;ok(await action(host,'kick',{playerId:removed}));assert.equal((await call('/api/rooms/'+host.code,null,sessions[3].token)).status,401);assert.equal((await get(host)).players.length,3);});
 await checked('isolated rooms and six-hour expiry',async()=>{const other=ok(await call('/api/rooms',{name:'別の部屋'}),201);assert.equal((await call('/api/rooms/'+other.room.code,null,host.token)).status,401);now=other.room.expiresAt+1;assert.equal((await call('/api/rooms/'+other.room.code,null,other.token)).status,404);});
 await checked('MCP initialization, discovery and rules',async()=>{const init=ok(await call('/mcp',{jsonrpc:'2.0',id:1,method:'initialize',params:{protocolVersion:'2025-03-26'}}));assert.equal(init.result.serverInfo.name,'ningen-magiretemasu');const list=ok(await call('/mcp',{jsonrpc:'2.0',id:2,method:'tools/list'}));assert.equal(list.result.tools.length,2);const rules=ok(await call('/mcp',{jsonrpc:'2.0',id:3,method:'tools/call',params:{name:'get_game_rules',arguments:{}}}));assert.ok(rules.result.content[0].text.includes('ニンゲン'));});
 console.log(tests.length+' scenarios passed.');
 await writeFile(new URL('../test-results.json',import.meta.url),JSON.stringify({testedAt:new Date(originalNow()).toISOString(),runtime:process.version,storage:'Node SQLite D1-compatible adapter',scenarios:tests},null,2),'utf8');
}finally{Date.now=originalNow;DB.raw.close();}
