const TTL=6*60*60*1000, MIN_PLAYERS=3, MAX_PLAYERS=8;
const alphabet='ABCDEFGHJKLMNPQRSTUVWXYZ23456789';
const textLength=s=>[...s].length;
const clean=s=>typeof s==='string'?s.trim().normalize('NFC'):'';
class GameError extends Error {constructor(message,status=400){super(message);this.status=status;}}
const fail=(s,status=400)=>{throw new GameError(s,status);};
const randomToken=()=>Array.from(crypto.getRandomValues(new Uint8Array(32)),b=>b.toString(16).padStart(2,'0')).join('');
async function hash(s){return Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s))),b=>b.toString(16).padStart(2,'0')).join('');}
function shuffle(a){a=[...a];for(let i=a.length-1;i>0;i--){let v=new Uint32Array(1),limit=Math.floor(4294967296/(i+1))*(i+1);do{crypto.getRandomValues(v);}while(v[0]>=limit);let j=v[0]%(i+1);[a[i],a[j]]=[a[j],a[i]];}return a;}
function nameOf(s){s=clean(s);if(textLength(s)<1||textLength(s)>12||/[\u0000-\u001f\u007f]/u.test(s))fail('名前は1〜12文字で入力してください。');return s;}
function codeOf(s){s=clean(s).toUpperCase();if(!/^[A-HJ-NP-Z2-9]{6}$/.test(s))fail('6文字のルームコードを入力してください。');return s;}
function json(data,status=200){return new Response(JSON.stringify(data),{status,headers:{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store','X-Content-Type-Options':'nosniff','Referrer-Policy':'no-referrer'}});}
function participant(room,tokenHash){return room.players.find(p=>p.tokenHash===tokenHash)||fail('この部屋への参加情報が見つかりません。',401);}
function hostOnly(room,p){if(room.hostId!==p.id)fail('この操作は主催者だけが行えます。',403);}
function round(room){return room.rounds?.[room.roundIndex];}
function checkRound(room,body){if(body.gameId!==(room.gameId||null)||body.roundId!==(round(room)?.id||null))fail('画面が更新されました。最新の状態を確認してください。',409);}
function beginRound(room,now){const r=round(room);room.phase='play';r.openAt=now+12000;r.deadline=now+45000;r.votes={};r.cards=shuffle([{id:crypto.randomUUID(),text:room.answers[r.authorId],human:true},...r.decoys.map(text=>({id:crypto.randomUUID(),text,human:false}))]);}
function reveal(room,now){if(room.phase!=='play')return;const r=round(room),correct=r.cards.find(c=>c.human).id;let wrong=0;for(const p of room.players){const vote=r.votes[p.id];if(p.id===r.authorId)continue;const hit=vote===correct;if(hit)p.score+=100;else if(vote)wrong++;}const author=room.players.find(p=>p.id===r.authorId);r.authorPoints=Math.round(200*wrong/(room.players.length-1));author.score+=r.authorPoints;r.revealedAt=now;room.phase='reveal';}
function view(room,p,revision,now){const r=round(room);const result={code:room.code,revision,phase:room.phase,gameId:room.gameId||null,expiresAt:room.expiresAt,serverNow:now,minPlayers:MIN_PLAYERS,maxPlayers:MAX_PLAYERS,roundIndex:room.roundIndex??0,roundCount:room.rounds?.length||0,hostId:room.hostId,players:room.players.map(x=>({id:x.id,name:x.name,score:x.score})),mine:{id:p.id,name:p.name,isHost:p.id===room.hostId},submittedCount:Object.keys(room.answers||{}).length};
 result.roundId=r?.id||null;result.generationMode=room.generationMode||'live';
 if(room.phase==='generation_error')result.generationError=room.generationError;
 if(room.phase==='writing'){const assignment=room.rounds.find(x=>x.authorId===p.id);result.mine.prompt=assignment.prompt;result.mine.submitted=Object.hasOwn(room.answers,p.id);result.mine.answer=room.answers[p.id]||'';}
 if(r&&['play','reveal','finished'].includes(room.phase)){result.round={id:r.id,prompt:r.prompt,cards:r.cards.map(c=>({id:c.id,text:c.text})),openAt:r.openAt,deadline:r.deadline,votedCount:Object.keys(r.votes).length};result.mine.role=p.id===r.authorId?'author':'seeker';result.mine.vote=r.votes[p.id]||null;
 if(room.phase!=='play'){result.round.aiSource=r.provenance?.kind==='llm_generated'?'live':'demo';result.round.correctCardId=r.cards.find(c=>c.human).id;result.round.authorId=r.authorId;result.round.authorPoints=r.authorPoints;result.round.votes=room.players.filter(x=>x.id!==r.authorId).map(x=>({playerId:x.id,cardId:r.votes[x.id]||null,correct:r.votes[x.id]===result.round.correctCardId}));}}
 if(room.phase==='finished'){result.highlights=room.rounds.map(x=>({prompt:x.prompt,answer:room.answers[x.authorId],authorName:room.players.find(p=>p.id===x.authorId).name,authorPoints:x.authorPoints,correctCount:Object.entries(x.votes).filter(([id,v])=>id!==x.authorId&&v===x.cards.find(c=>c.human).id).length}));}
 return result;}
async function rate(env,req,bucket,limit){const ip=req.headers.get('cf-connecting-ip')||'local';const now=Date.now(),slot=Math.floor(now/600000),key=bucket+':'+await hash(ip)+':'+slot;
 const row=await env.DB.prepare('INSERT INTO rate_limits(key,count,expires_at) VALUES (?,1,?) ON CONFLICT(key) DO UPDATE SET count=count+1 RETURNING count').bind(key,now+1200000).first();if(row.count>limit)fail('操作が多すぎます。少し待ってからお試しください。',429);}
async function createRoom(env,req,hostName){hostName=nameOf(hostName);await rate(env,req,'create',12);const now=Date.now(),token=randomToken(),p={id:crypto.randomUUID(),name:hostName,tokenHash:await hash(token),score:0};
 await env.DB.batch([env.DB.prepare('DELETE FROM rooms WHERE expires_at < ?').bind(now),env.DB.prepare('DELETE FROM rate_limits WHERE expires_at < ?').bind(now),env.DB.prepare('DELETE FROM generated_fingerprints WHERE expires_at < ?').bind(now)]);
 for(let attempt=0;attempt<5;attempt++){const code=Array.from(crypto.getRandomValues(new Uint8Array(6)),b=>alphabet[b%alphabet.length]).join('');const room={code,hostId:p.id,players:[p],phase:'lobby',generationMode:generationSettings(env).mode,expiresAt:now+TTL,answers:{},roundIndex:0};try{await env.DB.prepare('INSERT INTO rooms(code,state,revision,expires_at) VALUES (?,?,0,?)').bind(code,JSON.stringify(room),room.expiresAt).run();return {token,room:view(room,p,0,now)};}catch(e){if(!String(e).includes('UNIQUE'))throw e;}}fail('部屋を作れませんでした。もう一度お試しください。',503);}
async function transact(env,code,token,apply){const tokenHash=token?await hash(token):null;for(let attempt=0;attempt<8;attempt++){const now=Date.now(),row=await env.DB.prepare('SELECT state,revision,expires_at FROM rooms WHERE code = ?').bind(code).first();if(!row||row.expires_at<now)fail('この部屋は見つからないか、有効期限が切れています。',404);const room=JSON.parse(row.state),p=tokenHash?participant(room,tokenHash):null;let expired=room.phase==='play'&&now>=round(room).deadline;if(expired)reveal(room,now);if(room.phase==='preparing'&&now>room.generationDeadline){room.phase='generation_error';room.generationError='AIの準備に時間がかかりました。もう一度生成してください。';expired=true;}const result=await apply(room,p,now);if(result.readOnly&&!expired)return result.internal?{}:{room:view(room,p,row.revision,now)};
 const changed=await env.DB.prepare('UPDATE rooms SET state = ?, revision = revision + 1 WHERE code = ? AND revision = ?').bind(JSON.stringify(room),code,row.revision).run();if(changed.meta.changes===1){if(result.internal)return {};const {player,readOnly,...publicResult}=result;return {...publicResult,room:view(room,player||p,row.revision+1,now)};}}
 fail('同時に操作が入りました。もう一度お試しください。',409);}
async function gameApi(req,env,url,ctx){if(url.pathname==='/api/config'&&req.method==='GET')return json(generationSettings(env));if(!env.DB)fail('部屋のサーバー準備が完了していません。',503);
 if(url.pathname==='/api/rooms'&&req.method==='POST'){const b=await req.json();return json(await createRoom(env,req,b.name),201);}
 const match=url.pathname.match(/^\/api\/rooms\/([A-Z2-9]{6})(?:\/(join|action))?$/);if(!match)fail('ページが見つかりません。',404);const code=codeOf(match[1]);
 if(match[2]==='join'&&req.method==='POST'){await rate(env,req,'join',60);const b=await req.json(),name=nameOf(b.name),token=randomToken(),tokenHash=await hash(token);return json(await transact(env,code,null,(room)=>{if(room.phase!=='lobby')fail('ゲームが始まっています。次の部屋でご参加ください。',409);if(room.players.length>=MAX_PLAYERS)fail('この部屋は満員です。',409);if(room.players.some(p=>p.name===name))fail('同じ名前の人がいます。別の名前で参加してください。');const player={id:crypto.randomUUID(),name,tokenHash,score:0};room.players.push(player);return {token,player};}));}
 const token=req.headers.get('Authorization')?.replace(/^Bearer /,'');if(!/^[a-f0-9]{64}$/.test(token||''))fail('参加情報が必要です。',401);
 if(!match[2]&&req.method==='GET')return json(await transact(env,code,token,()=>({readOnly:true})));
 if(match[2]!=='action'||req.method!=='POST')fail('この操作は利用できません。',405);
 const b=await req.json();await rate(env,req,'action',400);
 if(b.type==='start'||b.type==='retry_generation'){
   const settings=generationSettings(env);if(!settings.ready)fail('生成サービスの接続がまだ設定されていません。',503);
   const topics=b.type==='start'?customTopics(b.customPrompts):null;let jobId;
   await transact(env,code,token,(room,p,now)=>{hostOnly(room,p);if(b.type==='start'&&room.phase!=='lobby')fail('ゲームはすでに始まっています。',409);if(b.type==='retry_generation'){checkRound(room,b);if(room.phase!=='generation_error')fail('再生成できる状態ではありません。',409);}if(room.players.length<MIN_PLAYERS)fail('3人以上で始められます。');if(topics&&topics.length>room.players.length)fail('お題の数を参加人数以下にしてください。');if((room.generationCount||0)>=30)fail('この部屋の生成回数の上限に達しました。');jobId=crypto.randomUUID();room.generationId=jobId;room.generationDeadline=now+90000;room.generationCount=(room.generationCount||0)+1;room.generationMode=settings.mode;room.gameId=crypto.randomUUID();room.answers={};room.roundIndex=0;room.rounds=[];if(topics)room.customPrompts=topics;room.players.forEach(p=>p.score=0);room.phase='preparing';room.generationError=null;return {};});
   await rate(env,req,'generation',12).catch(async e=>{await transact(env,code,null,room=>{if(room.generationId===jobId){room.phase='generation_error';room.generationError=e.message;}return {internal:true};});throw e;});
   const task=prepareGame(env,code,jobId);ctx?.waitUntil?.(task);await task;
   return json(await transact(env,code,token,()=>({readOnly:true})));
 }
 return json(await transact(env,code,token,(room,p,now)=>{
 checkRound(room,b);
 if(b.type==='reset'){hostOnly(room,p);room.phase='lobby';room.rounds=[];room.answers={};room.gameId=null;room.generationId=null;room.roundIndex=0;room.players.forEach(p=>p.score=0);return {};}
 if(b.type==='kick'){hostOnly(room,p);if(room.phase!=='lobby')fail('メンバーの変更は待合室で行ってください。',409);if(b.playerId===room.hostId)fail('主催者を外すことはできません。');if(!room.players.some(p=>p.id===b.playerId))fail('参加者が見つかりません。',404);room.players=room.players.filter(p=>p.id!==b.playerId);return {};}
 if(b.type==='submit'){if(room.phase!=='writing')fail('回答の受付は終わりました。',409);const answer=clean(b.answer);if(textLength(answer)<8||textLength(answer)>60||/[\u0000-\u001f\u007f]/u.test(answer))fail('回答は8〜60文字の一文で入力してください。');if(Object.hasOwn(room.answers,p.id))fail('回答は提出済みです。',409);const r=room.rounds.find(x=>x.authorId===p.id);r.decoys=shuffle(r.pool.filter(x=>normalizedContent(x)!==normalizedContent(answer))).slice(0,4);if(r.decoys.length!==4)fail('AI回答と重なりました。別の表現でお願いします。');room.answers[p.id]=answer;if(Object.keys(room.answers).length===room.players.length)beginRound(room,now);return {};}
 if(b.type==='vote'){if(room.phase!=='play')fail('投票は締め切られました。',409);const r=round(room);if(now<r.openAt)fail('まずカードを読みましょう。投票はまもなく始まります。',409);if(!r.cards.some(c=>c.id===b.cardId))fail('カードが見つかりません。');if(r.votes[p.id])fail('投票は確定済みです。',409);r.votes[p.id]=b.cardId;if(Object.keys(r.votes).length===room.players.length)reveal(room,now);return {};}
 hostOnly(room,p);
 if(b.type==='open_vote'){if(room.phase!=='play')fail('今は投票できません。',409);round(room).openAt=now;round(room).deadline=now+20000;return {};}
 if(b.type==='extend'){if(room.phase!=='play')fail('今は延長できません。',409);round(room).deadline=Math.min(round(room).deadline+30000,now+120000);return {};}
 if(b.type==='reveal'){if(room.phase!=='play')fail('答え合わせは済んでいます。',409);reveal(room,now);return {};}
 if(b.type==='next'){if(room.phase!=='reveal')fail('答え合わせのあとに進められます。',409);if(room.roundIndex===room.rounds.length-1)room.phase='finished';else{room.roundIndex++;beginRound(room,now);}return {};}
 if(b.type==='rematch'){if(room.phase!=='finished')fail('ゲーム終了後にもう一戦できます。',409);room.phase='lobby';room.rounds=[];room.answers={};room.gameId=null;room.roundIndex=0;room.players.forEach(p=>p.score=0);return {};}
 fail('不明な操作です。');}));}
const RULES={title:'ニンゲン、まぎれてます。',players:'3〜8人（おすすめ4〜6人）',flow:['部屋のURLを友達に共有する','主催者が自由なお題を入力するか、AIに新しいお題を任せる','AIがその場で回答を生成。全員が別々のお題に8〜60文字で回答する','友達の回答1枚とAI回答4枚を読む','話し合って秘密投票する。作者もカモフラージュ投票できる','作者と正解を公開。全員が一度ずつ作者になる'],scoring:'探す側は正解100点。作者は200×誤答した人数÷探す側の人数（四捨五入）。未投票は作者の加点対象外。',privacy:'投稿は部屋の参加者に表示。人間の回答は生成APIに送らない。自由なお題と過去のAI回答は生成APIに送る。部屋は6時間で利用終了、期限切れデータは次の部屋作成時に削除。生成素材の重複確認用ハッシュは最大30日間照合される。デモモードは固定素材。'};
async function mcp(req,env){const b=await req.json();if(b.method==='notifications/initialized'||b.id===undefined)return new Response(null,{status:202});let result;
 if(b.method==='initialize')result={protocolVersion:'2025-03-26',capabilities:{tools:{}},serverInfo:{name:'ningen-magiretemasu',version:'1.0.0'}};
 else if(b.method==='ping')result={};
 else if(b.method==='tools/list')result={tools:[{name:'get_game_rules',description:'日本語パーティーゲームの遊び方と得点を読む。',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true}},{name:'create_party_room',description:'友達と遊ぶ部屋を作る。host_launch_urlは主催者専用、invite_urlを友達に共有する。',inputSchema:{type:'object',properties:{host_name:{type:'string',minLength:1,maxLength:12}},required:['host_name'],additionalProperties:false},annotations:{readOnlyHint:false,destructiveHint:false,idempotentHint:false}}]};
 else if(b.method==='tools/call'){try{let data;if(b.params?.name==='get_game_rules')data=RULES;else if(b.params?.name==='create_party_room'){if(!env.DB)fail('サーバー準備中です。',503);const created=await createRoom(env,req,b.params.arguments?.host_name),origin=new URL(req.url).origin;data={code:created.room.code,host_launch_url:origin+'/?room='+created.room.code+'#session='+created.token,invite_url:origin+'/?room='+created.room.code,expires_at:new Date(created.room.expiresAt).toISOString()};}else fail('不明なツールです。');result={content:[{type:'text',text:JSON.stringify(data)}]};}catch(e){if(!(e instanceof GameError))throw e;result={isError:true,content:[{type:'text',text:e.message}]};}}
 else return json({jsonrpc:'2.0',id:b.id,error:{code:-32601,message:'Method not found'}});
 return json({jsonrpc:'2.0',id:b.id,result});}
export default {async fetch(req,env,ctx){try{const url=new URL(req.url);if(req.method==='POST'){const origin=req.headers.get('origin');if(origin&&origin!==url.origin)fail('別のサイトからの操作はできません。',403);const declared=Number(req.headers.get('content-length')||0);if(declared>8192)fail('入力が長すぎます。',413);const body=await req.text();if(new TextEncoder().encode(body).length>8192)fail('入力が長すぎます。',413);req=new Request(req,{body});}
 if(url.pathname.startsWith('/api/'))return await gameApi(req,env,url,ctx);
 if(url.pathname==='/mcp'&&req.method==='POST')return await mcp(req,env);
 if(url.pathname==='/health')return json({ok:true,storage:!!env.DB});
 if(url.pathname==='/'&&req.method==='GET')return new Response(PAGE,{headers:{'Content-Type':'text/html; charset=utf-8','Cache-Control':'no-cache','X-Content-Type-Options':'nosniff','Referrer-Policy':'no-referrer','Content-Security-Policy':"default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; connect-src 'self'; base-uri 'none'; form-action 'self'; frame-ancestors 'self' https://chatgpt.com https://*.chatgpt.com"}});
 return json({error:'ページが見つかりません。'},404);
 }catch(e){if(e instanceof GameError)return json({error:e.message},e.status);if(e instanceof GenerationError)return json({error:e.message},400);if(e instanceof SyntaxError)return json({error:'入力を読み取れませんでした。'},400);console.error('Game request failed',e.name);return json({error:'サーバーでエラーが起きました。少し待ってお試しください。'},500);}}};
