(()=>{'use strict';
const app=document.querySelector('#app'),notice=document.querySelector('#notice'),status=document.querySelector('#connection');
let session=null,state=null,selected=null,busy=false,pollTimer,offset=0,lastSuccess=0,toastTimer,epoch=0,storageWarned=false,config=null;
const memory=new Map(),controllers=new Set();
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const read=(k,f=null)=>{if(memory.has(k))return memory.get(k)??f;try{return JSON.parse(localStorage.getItem(k))??f;}catch{return f;}};
const save=(k,v)=>{memory.set(k,v);try{localStorage.setItem(k,JSON.stringify(v));}catch{if(!storageWarned){storageWarned=true;toast('このブラウザでは参加情報を保存できません。画面を閉じずに遊んでください。',true);}}};
function setSession(s){epoch++;controllers.forEach(c=>c.abort());clearTimeout(pollTimer);session=s;state=null;selected=null;busy=false;}
function toast(message,error=false){clearTimeout(toastTimer);notice.textContent=message;notice.className='notice'+(error?' error':'');notice.hidden=false;toastTimer=setTimeout(()=>notice.hidden=true,6000);}
const storageKey=code=>'ningen-session-'+code;
function apply(data){if(!data.room||data.room.code!==session?.code)return;if(state&&data.room.revision<state.revision)return;offset=data.room.serverNow-Date.now();lastSuccess=Date.now();status.textContent='● 接続中';if(!state||state.revision!==data.room.revision){const transition=!state||state.phase!==data.room.phase||state.gameId!==data.room.gameId||state.roundId!==data.room.roundId;const sameRound=state&&state.gameId===data.room.gameId&&state.roundId===data.room.roundId;const writing=state?.phase==='writing'&&data.room.phase==='writing'&&sameRound&&!state.mine.submitted&&!data.room.mine.submitted;state=data.room;selected=state.mine.vote||(sameRound&&state.round?.cards.some(c=>c.id===selected)?selected:null);if(writing){const progress=app.querySelector('#submit-progress');if(progress)progress.textContent=state.submittedCount+' / '+state.players.length+' 人が提出済み';}else{render();if(transition)window.scrollTo({top:0,behavior:'instant'});}}else state=data.room;tick();}
async function request(path,body,auth=true){const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),body?.type==='start'||body?.type==='retry_generation'?90000:15000);controllers.add(controller);try{const r=await fetch(path,{method:body?'POST':'GET',cache:'no-store',headers:{...(body?{'Content-Type':'application/json'}:{}),...(auth&&session?{Authorization:'Bearer '+session.token}:{})},...(body?{body:JSON.stringify(body)}:{}),signal:controller.signal});let data;try{data=await r.json();}catch{throw new Error('通信の返答を読み取れませんでした。');}if(!r.ok){const e=new Error(data.error||'通信に失敗しました。');e.status=r.status;throw e;}return data;}catch(e){if(e.name==='AbortError')throw new Error('通信に時間がかかっています。接続が戻ったら状態を確認します。');throw e;}finally{clearTimeout(timer);controllers.delete(controller);}}
async function poll(){clearTimeout(pollTimer);if(!session)return;const turn=epoch,s=session;try{const data=await request('/api/rooms/'+s.code);if(turn!==epoch)return;apply(data);}catch(e){if(turn!==epoch)return;status.textContent='◌ 再接続中';if(e.status===401||e.status===404){toast(e.message,true);save(storageKey(s.code),null);setSession(null);landing(s.code);return;}}if(turn===epoch)pollTimer=setTimeout(poll,1600);}
async function restore(s){if(!s?.code||!s?.token)return;setSession(s);const turn=epoch;app.innerHTML='<div class="loading"><span>▦</span><p>部屋に戻っています…</p><button class="secondary" id="restore-home">トップへ</button></div>';document.querySelector('#restore-home').onclick=()=>{setSession(null);landing();};try{const data=await request('/api/rooms/'+s.code);if(turn!==epoch)return;apply(data);save(storageKey(s.code),s);save('ningen-last-room',s.code);poll();}catch(e){if(turn!==epoch)return;toast(e.message,true);if(e.status===401||e.status===404){save(storageKey(s.code),null);setSession(null);landing(s.code);}else{status.textContent='◌ 再接続中';pollTimer=setTimeout(poll,1800);}}}
async function enter(kind){if(busy)return;const turn=epoch,name=document.querySelector(kind==='create'?'#host-name':'#join-name').value.trim(),code=document.querySelector('#room-code').value.trim().toUpperCase();busy=true;document.querySelectorAll('form button').forEach(b=>b.disabled=true);try{const data=await request(kind==='create'?'/api/rooms':'/api/rooms/'+code+'/join',{name},false);if(turn!==epoch)return;setSession({code:data.room.code,token:data.token});save(storageKey(session.code),session);save('ningen-last-room',session.code);save('ningen-name',name);history.replaceState(null,'','/?room='+session.code);apply(data);poll();}catch(e){if(turn===epoch)toast(e.message,true);}finally{busy=false;document.querySelectorAll('form button').forEach(b=>b.disabled=false);}}
async function action(type,extra={}){if(!session||!state||(busy&&!(type==='reset'&&state.phase==='preparing')))return;if(type==='start')extra.customPrompts=app.querySelector('#custom-prompts')?.value||'';const turn=epoch,s=session;busy=true;const buttons=[...app.querySelectorAll('button')];buttons.forEach(b=>b.disabled=true);try{const data=await request('/api/rooms/'+s.code+'/action',{type,gameId:state.gameId,roundId:state.roundId,...extra});if(turn===epoch)apply(data);}catch(e){if(turn!==epoch)return;toast(e.message,true);try{const data=await request('/api/rooms/'+s.code);if(turn===epoch)apply(data);}catch{}}finally{if(turn===epoch){busy=false;if(state)render();}}}
function invite(){return location.origin+'/?room='+state.code;}
async function copyInvite(){const url=invite();try{await navigator.clipboard.writeText(url);toast('参加URLをコピーしました。友達に送ってください。');}catch{toast('参加URL：'+url);}}
function roomBar(){return '<div class="room-bar"><div class="room-pill"><span>ROOM</span><strong class="room-code">'+state.code+'</strong></div><div class="room-actions"><button class="quiet" data-copy>招待URLをコピー ↗</button><button class="quiet" data-home>トップへ</button></div></div>';}
function players(){return '<div class="player-list">'+state.players.map((p,i)=>'<div class="player"><div class="avatar">'+['▦','⊙','◉','⌘','⦿','◎','◈','▥'][i]+'</div><div><div class="player-name">'+esc(p.name)+(p.id===state.mine.id?' <small>あなた</small>':'')+'</div><div class="player-score">'+(state.phase==='lobby'?(p.id===state.hostId?'主催者':'参加者'):p.score+' pt')+'</div></div></div>').join('')+'</div>';}
function landing(code=''){clearTimeout(pollTimer);const name=esc(read('ningen-name','')),recent=read('ningen-last-room'),resume=recent&&read(storageKey(recent));status.textContent='ブラウザで、みんなと。';
app.innerHTML=(resume?'<div class="reconnect"><span>参加中の部屋 '+esc(recent)+' へ戻れます。</span><button class="secondary" id="resume">部屋に戻る</button></div>':'')+'<section class="hero"><div><div class="live-label">AI HIDE & SEEK PARTY</div><h1>ニンゲン、<br><span class="highlight">まぎれてます。</span></h1><p class="hero-copy">五枚の回答に、一枚だけ友達の言葉。<br>見抜くか。見抜かれずに、だますか。<br>「……それ、俺が書いたんだけど。」が始まる。</p><div class="chips"><span>◉ 3〜8人</span><span>⌁ スマホ・PC</span><span>♡ 登録不要</span></div></div><div class="stage" aria-label="ゲームのカードのイメージ"><span class="stage-tag">ONE OF US IS HUMAN.</span><div class="mini-face">• ▰ •</div><div class="demo-card back"><small>CARD A</small>起床の意思を尊重し、<br>通知を控えています。</div><div class="demo-card middle"><small>CARD B</small>朝の定義は、<br>柔軟に変更できます。</div><div class="demo-card front"><small>CARD C</small>三度目の二度寝から、<br>本気を出します。<span class="human-stamp">ニンゲン？</span></div><span class="stage-label">DEMO / 表示イメージ</span></div></section><section class="join-zone"><form class="panel" id="create-form"><div class="panel-head"><span class="number">01</span><div><h2>部屋をつくる</h2><p>主催者はこちら。友達を呼ぼう。</p></div></div><label for="host-name">あなたの名前</label><input id="host-name" maxlength="12" placeholder="例：たろう" autocomplete="nickname" required value="'+name+'"><button class="primary full">部屋をつくる <span>→</span></button><p class="fine">無料で遊べます。名前だけで準備完了。</p></form><form class="panel" id="join-form"><div class="panel-head"><span class="number">02</span><div><h2>部屋にはいる</h2><p>招待されたら、こちらから。</p></div></div><label for="join-name">あなたの名前</label><input id="join-name" maxlength="12" placeholder="例：はな" autocomplete="nickname" required value="'+name+'"><div class="input-row"><div><label for="room-code">ルームコード</label><input id="room-code" class="code-input" maxlength="6" minlength="6" pattern="[A-Za-z2-9]{6}" placeholder="ABC123" value="'+esc(code)+'" required autocomplete="off" autocapitalize="characters"></div><button class="primary">参加する →</button></div></form></section><div class="bottom-note"><strong>話しながら、遊ぼう。</strong><span>同じ部屋でも、いつものオンライン通話でも。全員が自分の端末でカードを読めます。</span></div>';
document.querySelector('#create-form').onsubmit=e=>{e.preventDefault();enter('create');};document.querySelector('#join-form').onsubmit=e=>{e.preventDefault();const c=document.querySelector('#room-code').value.toUpperCase();const saved=read(storageKey(c));if(saved)restore(saved);else enter('join');};document.querySelector('#resume')?.addEventListener('click',()=>restore(resume));if(code)document.querySelector('#join-name').focus();loadConfig();}
async function loadConfig(){try{config=await request('/api/config',null,false);}catch{return;}if(!state&&app.querySelector('.hero')){app.querySelector('.hero').insertAdjacentHTML('afterend','<p class="service-note fine">'+(config.mode==='demo'?'デモモード：固定素材で操作を試せます。':'お題から、その場でAIが回答をつくります。'+(!config.ready?' 生成サービスは接続準備中です。':''))+'</p>');}}
function render(){if(!state)return;let html=roomBar();
if(state.phase==='lobby'){html+='<div class="game-title"><span class="eyebrow">BACKSTAGE / 待ち合わせ</span><h2>あとは、友達を呼ぶだけ。</h2><p>みんなが揃ったら、一文ずつ書いてもらいます。<br>全員が一度ずつ「潜伏役」になる、一巡のゲーム。</p></div>'+players()+'<div class="lobby-invite"><b>'+state.players.length+' / 8 人が参加中</b><br><code>'+esc(invite())+'</code></div><div class="center-action">'+(state.mine.isHost?'<button class="primary" data-action="start" '+(state.players.length<3?'disabled':'')+'>このメンバーで始める →</button><p class="small">3人から遊べます。おすすめは4〜6人。</p>':'<p>主催者が始めるまで、ちょっと待とう。</p>')+'</div>';}
if(state.phase==='writing'){html+='<div class="game-title"><span class="eyebrow">WRITE / 人間のふりをする、AIのふりをする</span><h2>友達にバレない、一文を。</h2><p>全員に違うお題が届いています。書き終わったら、AIの回答に混ぜます。</p></div><div class="panel writing-panel"><span class="eyebrow">あなたのお題</span><div class="prompt">'+esc(state.mine.prompt)+'</div>'+(state.mine.submitted?'<div class="waiting"><b>提出できました ✓</b><p>'+esc(state.mine.answer)+'</p><span class="small">全員が書き終わるまで待っています。</span></div>':'<form id="answer-form"><label for="answer">あなたの回答（8〜60文字）</label><textarea id="answer" maxlength="120" placeholder="ちょっと機械っぽく？ いつもの自分っぽく？" required></textarea><div class="count-row"><span>整えすぎず、あなたの言葉で。</span><span id="char-count">0 / 60</span></div><button class="primary full" id="submit-answer" disabled>この一文を、紛れ込ませる →</button></form>')+'<p class="small" style="text-align:center;margin-top:24px">'+state.submittedCount+' / '+state.players.length+' 人が提出済み</p></div>';}
if(state.phase==='play'||state.phase==='reveal'){const r=state.round,isReveal=state.phase==='reveal';html+='<div class="toolbar"><div class="phase-label"><span class="timer" id="timer">--</span><span id="phase-text">読んで、話し合って。</span></div><span class="progress">ROUND '+(state.roundIndex+1)+' / '+state.roundCount+' · <span id="voted">'+r.votedCount+' / '+state.players.length+' 人が投票</span></span></div><h2 class="round-prompt">'+esc(r.prompt)+'</h2>'+(isReveal?'':'<div class="role-strip '+(state.mine.role==='author'?'author':'')+'">'+(state.mine.role==='author'?'<b>あなただけの秘密：この回答の作者です。</b><br>別のカードを疑うふりもOK。カモフラージュ投票でまぎれよう。':'この中に一枚だけ、友達の回答があります。<b>ニンゲンを見つけよう。</b>')+'</div>')+'<div class="cards">'+r.cards.map((c,i)=>'<button class="answer-card '+(isReveal?(c.id===r.correctCardId?'correct':''):(selected===c.id?'selected':''))+'" data-card="'+c.id+'" '+(isReveal||state.mine.vote?'disabled':'')+' aria-pressed="'+(selected===c.id)+'"><span class="card-letter">'+String.fromCharCode(65+i)+'</span><span class="card-text">'+esc(c.text)+'</span>'+(isReveal?'<span class="source-tag '+(c.id===r.correctCardId?'human':'')+'">'+(c.id===r.correctCardId?'ニンゲン / '+esc(state.players.find(p=>p.id===r.authorId).name):(r.aiSource==='live'?'AI / このゲームで生成':'AI / デモ素材'))+'</span>':'')+'</button>').join('')+'</div>';
if(!isReveal)html+='<div class="vote-action">'+(state.mine.vote?'<p><b>投票を確定しました ✓</b></p><p class="small">答え合わせまで、顔に出さずに。</p>':'<button class="primary" id="vote-confirm" '+(!selected?'disabled':'')+'>このカードに、秘密投票 →</button><p class="small" id="vote-hint">投票先は答え合わせまで非公開です。</p>')+'</div>'+(state.mine.isHost?'<div class="host-controls"><button class="secondary" data-action="open_vote">話し合いを終えて投票へ</button><button class="secondary" data-action="extend">30秒延長</button><button class="secondary" data-action="reveal">締め切って答え合わせ</button></div>':'');
else{const me=r.votes.find(v=>v.playerId===state.mine.id);html+='<div class="reveal-banner"><span class="eyebrow">HUMAN DETECTED.</span><h2>「それ、'+esc(state.players.find(p=>p.id===r.authorId).name)+'が書きました。」</h2><p>'+(state.mine.role==='author'?'あなたの潜伏：＋'+r.authorPoints+' pt':me?.correct?'見抜いた！ あなたに＋100 pt':'今回は、まぎれられました。')+' · 作者の潜伏得点 ＋'+r.authorPoints+' pt</p></div><div class="vote-results">'+r.votes.map(v=>'<span class="result-chip '+(v.correct?'hit':'')+'">'+esc(state.players.find(p=>p.id===v.playerId).name)+' → '+(v.cardId?String.fromCharCode(65+r.cards.findIndex(c=>c.id===v.cardId)):'未投票')+(v.correct?' ✓':'')+'</span>').join('')+'</div>'+players()+'<div class="center-action">'+(state.mine.isHost?'<button class="primary" data-action="next">'+(state.roundIndex===state.roundCount-1?'最終結果へ':'次のニンゲンを探す')+' →</button>':'<p class="small">主催者が次へ進めるまでお待ちください。</p>')+'</div>';}}
if(state.phase==='finished'){const ranking=[...state.players].sort((a,b)=>b.score-a.score),highest=ranking[0].score,best=[...state.highlights].sort((a,b)=>b.authorPoints-a.authorPoints)[0];html+='<div class="game-title"><span class="eyebrow">THAT WAS VERY HUMAN.</span><h2>みんな、ちゃんと怪しかった。</h2><p>'+ranking.filter(p=>p.score===highest).map(p=>esc(p.name)).join(' ＆ ')+'、おめでとう。</p></div><div class="rank-list">'+ranking.map((p,i)=>'<div class="rank"><span class="rank-num">'+(1+ranking.filter(q=>q.score>p.score).length)+'</span><span class="rank-name">'+esc(p.name)+'</span><span class="rank-score">'+p.score+'<small> pt</small></span></div>').join('')+'</div><div class="memories"><div class="memory"><span class="eyebrow">潜伏名人 / '+esc(best.authorName)+'</span><p class="quote">「'+esc(best.answer)+'」</p><p class="small">'+esc(best.prompt)+'<br>作者の得点 '+best.authorPoints+' pt</p></div><div class="memory"><span class="eyebrow">今日のニンゲンたち</span><p class="quote">AIを疑って、<br>友達が見つかった。</p><p class="small">'+state.roundCount+'個のお題で遊びました。<br>次は、もっと上手にまぎれられるかも。</p></div></div><div class="center-action">'+(state.mine.isHost?'<button class="primary" data-action="rematch">同じメンバーで、もう一戦 →</button>':'<p class="small">主催者が「もう一戦」を選ぶと待合室へ戻ります。</p>')+'</div>';}
if(state.phase==='preparing'||state.phase==='generation_error'){html+='<div class="game-title"><span class="eyebrow">'+(state.phase==='preparing'?'AI IS WRITING.':'TRY AGAIN.')+'</span><h2>'+(state.phase==='preparing'?'新しい回答を、つくっています。':'もう一度、新しい回答を。')+'</h2><p>'+(state.phase==='preparing'?'毎回、新しいお題と回答を用意します。<br>少し待っている間に、みんなとおしゃべりを。':esc(state.generationError))+'</p></div><div class="center-action">'+(state.mine.isHost?(state.phase==='generation_error'?'<button class="primary" data-action="retry_generation">もう一度生成 →</button>':'')+'<div class="host-controls"><button class="secondary" data-action="reset">待合室へ戻す</button></div>':'<p class="small">主催者の準備ができるまでお待ちください。</p>')+'</div>';}
app.innerHTML='<section class="game">'+html+'</section>';
if(state.phase==='lobby'&&state.mine.isHost){app.querySelector('.center-action').insertAdjacentHTML('beforebegin','<form class="panel writing-panel" id="topics-form"><label for="custom-prompts">自分のお題で遊ぶ（任意）</label><textarea id="custom-prompts" maxlength="970" placeholder="1行に1つ、参加人数分まで。\n例：宇宙のコンビニで売ってはいけない商品"></textarea><p class="fine">空欄なら、AIが新しいお題を作ります。自由なお題は生成サービスへ送られます。名前や連絡先は書かないでください。</p></form>');const field=app.querySelector('#custom-prompts');field.value=read('ningen-topics-'+state.code,'');field.oninput=()=>save('ningen-topics-'+state.code,field.value);app.querySelector('#topics-form').onsubmit=e=>e.preventDefault();}
if(state.generationMode==='demo')app.querySelector('.room-bar').insertAdjacentHTML('afterend','<p class="fine" style="text-align:center">デモモード · AI回答は固定素材です。ライブ生成は接続されていません。</p>');
if(state.phase==='writing'){const progress=app.querySelector('.writing-panel > p');if(progress)progress.id='submit-progress';if(state.mine.isHost)app.querySelector('.writing-panel').insertAdjacentHTML('beforeend','<div class="host-controls"><button class="secondary" id="reset-writing">回答受付を中止して待合室へ</button></div>');}
if(state.phase==='lobby'&&state.mine.isHost){app.querySelectorAll('.player').forEach((el,i)=>{const p=state.players[i];if(p.id!==state.hostId){const b=document.createElement('button');b.className='quiet';b.title=p.name+'を部屋から外す';b.setAttribute('aria-label',b.title);b.textContent='×';b.onclick=()=>{if(confirm(p.name+'を部屋から外しますか？'))action('kick',{playerId:p.id});};el.appendChild(b);}});}
bind();tick();}
function bind(){app.querySelector('#reset-writing')?.addEventListener('click',()=>{if(confirm('提出済みの回答を破棄し、全員で待合室に戻りますか？'))action('reset');});app.querySelector('[data-copy]')?.addEventListener('click',copyInvite);app.querySelector('[data-home]')?.addEventListener('click',()=>{setSession(null);history.replaceState(null,'','/');landing();});app.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>action(b.dataset.action));app.querySelectorAll('[data-card]').forEach(b=>b.onclick=()=>{selected=b.dataset.card;app.querySelectorAll('[data-card]').forEach(x=>{x.classList.toggle('selected',x.dataset.card===selected);x.setAttribute('aria-pressed',x.dataset.card===selected);});tick();});app.querySelector('#vote-confirm')?.addEventListener('click',()=>action('vote',{cardId:selected}));
const answer=app.querySelector('#answer');if(answer){const draftKey='ningen-draft-'+state.code+'-'+state.gameId;answer.value=read(draftKey,'');const count=()=>{const n=[...answer.value.trim()].length;app.querySelector('#char-count').textContent=n+' / 60';app.querySelector('#submit-answer').disabled=n<8||n>60||busy;save(draftKey,answer.value);};answer.oninput=count;count();app.querySelector('#answer-form').onsubmit=e=>{e.preventDefault();action('submit',{answer:answer.value});};}}
function tick(){if(session&&lastSuccess&&Date.now()-lastSuccess>8000)status.textContent='◌ 再接続中';if(state?.phase!=='play')return;const now=Date.now()+offset,wait=Math.max(0,Math.ceil((state.round.openAt-now)/1000)),left=Math.max(0,Math.ceil((state.round.deadline-now)/1000));const timer=app.querySelector('#timer'),label=app.querySelector('#phase-text');if(timer)timer.textContent=String(wait||left).padStart(2,'0');if(label)label.textContent=wait?'まずは読む時間':'話し合いながら、秘密投票';const button=app.querySelector('#vote-confirm');if(button)button.disabled=busy||!selected||wait>0||left<=0;const hint=app.querySelector('#vote-hint');if(hint)hint.textContent=wait?'投票はあと'+wait+'秒で始まります。':'投票先は答え合わせまで非公開です。';}
document.querySelector('#rules-open').onclick=()=>document.querySelector('#rules').showModal();document.querySelector('#rules-close').onclick=()=>document.querySelector('#rules').close();document.querySelector('#rules').addEventListener('click',e=>{if(e.target===e.currentTarget){const r=e.currentTarget.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)e.currentTarget.close();}});
setInterval(tick,250);document.addEventListener('visibilitychange',()=>{if(!document.hidden&&session)poll();});window.addEventListener('online',()=>{if(session)poll();});
const code=(new URLSearchParams(location.search).get('room')||'').toUpperCase(),fragment=new URLSearchParams(location.hash.slice(1)),token=fragment.get('session');if(token){history.replaceState(null,'','/?room='+encodeURIComponent(code));if(/^[a-f0-9]{64}$/.test(token)&&/^[A-Z2-9]{6}$/.test(code))restore({code,token});else landing(code);}else if(code&&read(storageKey(code)))restore(read(storageKey(code)));else landing(code);
})();
